
// Generated by https://quicktype.io


export interface login {    
    nombreUsuario: string,
    password: string
}

export interface UserRegistro {   
    id?:  string,
    nombreUsuario: string,
    nombre: string,
    password: string,
    role: string      
}

// {
//     "id": "2c9a098d-a61b-4aa7-a0b9-2f8f948f78f1",
//     "userName": "Emilio@gmail.com",
//     "nombre": "emilio coquies",
//     "password": null,
//     "role": null
//   }

export interface UsuarioResponse {
    statusCode:    number;
    isSuccess:     boolean;
    errorMessages: any[];
    result:        Result;
}

export interface Result {
    usuario: UsuarioClass;
    token:   string;
}

export interface UsuarioClass {
    id:       string;
    userName: string;
    nombre:   string;
}


