
// Generated by https://quicktype.io

export interface CacheStore {
    categoria:   Categoria[];
}

export interface Categoria {
    id:     number;
    nombre: string;
}

export interface Clasificacion {
    id:           number;
    value:        string;
}